### ISSUE TITLE
Please make data available

### ISSUE THREAD

**Issue by alephnull** [cis-india/censorwatch#1]
There is traffic engineering, and there are privacy violations. I don't suppose that this data will be very popular with the ISPs but making it available would be hugely useful for consumers.

**Comment by gurshabad** [comment]
Apologies for the delay. The data from Censorwatch is finally available [here](https://github.com/cis-india/censorwatch/releases/tag/1.0.0). 

Our paper (that analyses the data) can be accessed [here](https://www.petsymposium.org/foci/2023/foci-2023-0006.pdf).

Hope you find the data useful, and please reach out if you have any questions!
